package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

/* loaded from: classes.dex */
public final class zzrg<R extends Result> extends OptionalPendingResult<R> {

    /* renamed from: zi */
    private final zzqe<R> f3293zi;

    public zzrg(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzqe)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.f3293zi = (zzqe) pendingResult;
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await() {
        return this.f3293zi.await();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await(long j, TimeUnit timeUnit) {
        return this.f3293zi.await(j, timeUnit);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void cancel() {
        this.f3293zi.cancel();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public R get() {
        if (isDone()) {
            return await(0L, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public boolean isCanceled() {
        return this.f3293zi.isCanceled();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public boolean isDone() {
        return this.f3293zi.isReady();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.f3293zi.setResultCallback(resultCallback);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.f3293zi.setResultCallback(resultCallback, j, timeUnit);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.f3293zi.then(resultTransform);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void zza(PendingResult.zza zzaVar) {
        this.f3293zi.zza(zzaVar);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public Integer zzaqf() {
        return this.f3293zi.zzaqf();
    }
}
